version: '3'

services:

  nginx:
    container_name: pdi-nginx
    restart: always
    build:
      context: ./devops/nginx
      dockerfile: Dockerfile
    ports:
      - 3000:80
      - 3001:443
    volumes:
      - ./src:/var/www/html/src
      - ./test:/var/www/html/test
    links:
      - php-fpm
    networks:
      - code-network

  php-fpm:
    container_name: pdi-phpfpm
    restart: always
    build:
      context: ./devops/php-fpm
      dockerfile: Dockerfile
    expose:
      - "9000" 
    volumes:
      - ./:/var/www/html
    networks:
      - code-network

networks:
    code-network:
        driver: bridge
